### ISSUE TITLE
Css email newsletter

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-mod_newsletter#6]
mettre la feuille de style de la newsletter

**Comment by verovs** [comment]
J'ai vu passer des tests NL. Dis nous qd c'est fini de ton côté stp :)  @CrymSonir

**Comment by CrymSonir** [comment]
Oui ça fonctionne bien sans problème, l'utilisation de feuille css me semble pas obligatoire d'ailleurs.

L'outil d'édition de texte de la newsletter est hyper complet y'a vraiment tout.

**Comment by verovs** [comment]
Deux questions pour qd tu auras le temps! (pas du tout du tout pressé)
1) la newsletter que j'ai créée n'a pas le style que t'as défini, (les bandeaux img en haut par exemple) pourtant j'ai choisi la feuille de style "testcss" :
https://mooc-test.tela-botanica.org/mod/newsletter/view.php?id=3261&action=readissue&issue=17
2) tu pourras m'envoyer le fichier css qd il sera fini ? (je ne trouve pas comment le telecharger ><')  comme ça je pourrai le modifier par la suite : par exemple  il faudra lui ajouter de la margin left/right pour diminuer la zone de txte

**Comment by CrymSonir** [comment]
1. Les Bandeaux sont de simples intégrations d'images faites via l'éditeur WYSIWYG, elles ne sont donc pas contenues dans le fichier css, le fichier css contient uniquement une ligne de code permettant de passer les titres en bleu ( pour tester que le fichier fonctionnait bien ).
2. Tu peux retrouver le fichier CSS directement dans les options de la newsletter par exemple : https://mooc-test.tela-botanica.org/course/modedit.php?update=3261&return=1

**Comment by verovs** [comment]
merci !
